In [62]:
import numpy as np

num1 = np.array([1,2,3])
num2 = np.array([0,1,2])
num3 = np.array([-1,-1,-1])
indepensible = np.array([0,0,0])
bool = False
for a in range(1,100):
    if(bool):break
    for b in range(1,100):
        if(bool):break
        for c in range(1,100):
            result = a * num1 + b * num2 + c * num3
            if(result[0] == indepensible[0] & result[1] == indepensible[1] & result[2] == indepensible[2]):
                print("its indepensible")
                bool = True
                break

print(a)
print(b)
print(c)

its indepensible
2
2
1


In [63]:
(a*num1)+(b*num2)+(num3 * c)

array([1, 5, 9])

In [64]:
indepensible

array([0, 0, 0])

In [65]:
result

array([0, 2, 4])

In [3]:
import numpy as np

u = np.array([[-0.27], [0.4],[0.8]])
u

array([[-0.27],
       [ 0.4 ],
       [ 0.8 ]])

In [16]:
2*u*u.T

array([[ 0.1458, -0.216 , -0.432 ],
       [-0.216 ,  0.32  ,  0.64  ],
       [-0.432 ,  0.64  ,  1.28  ]])

In [22]:
np.array([[1, 0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.array([[0.86, 0.2,0.42],[0.2,0.68,-0.64],[0.42,-0.64,-0.28]]) * np.array([[7, 2,0],[2,1,3],[4,8,3]])

array([[ 6.02,  0.4 ,  0.  ],
       [ 0.4 ,  0.68, -1.92],
       [ 1.68, -5.12, -0.84]])